//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All Supported Files 的本地化字符串。
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit the application? 的本地化字符串。
        /// </summary>
        public static string ConfirmExitMessage {
            get {
                return ResourceManager.GetString("ConfirmExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Confirmation 的本地化字符串。
        /// </summary>
        public static string ConfirmExitTitle {
            get {
                return ResourceManager.GetString("ConfirmExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity 的本地化字符串。
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string Fit {
            get {
                return ResourceManager.GetString("Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Geometry 的本地化字符串。
        /// </summary>
        public static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2D Optimized 的本地化字符串。
        /// </summary>
        public static string k2DOptimized {
            get {
                return ResourceManager.GetString("k2DOptimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flat Shaded 的本地化字符串。
        /// </summary>
        public static string kFlatShaded {
            get {
                return ResourceManager.GetString("kFlatShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flat Shaded with Wireframe 的本地化字符串。
        /// </summary>
        public static string kFlatShadedWithWireframe {
            get {
                return ResourceManager.GetString("kFlatShadedWithWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gouraud Shaded 的本地化字符串。
        /// </summary>
        public static string kGouraudShaded {
            get {
                return ResourceManager.GetString("kGouraudShaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gouraud Shaded with Wireframe 的本地化字符串。
        /// </summary>
        public static string kGouraudShadedWithWireframe {
            get {
                return ResourceManager.GetString("kGouraudShadedWithWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden Line 的本地化字符串。
        /// </summary>
        public static string kHiddenLine {
            get {
                return ResourceManager.GetString("kHiddenLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wireframe 的本地化字符串。
        /// </summary>
        public static string kWireframe {
            get {
                return ResourceManager.GetString("kWireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeftButtonDragger 的本地化字符串。
        /// </summary>
        public static string LeftButtonDragger {
            get {
                return ResourceManager.GetString("LeftButtonDragger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MiddleButtonDragger 的本地化字符串。
        /// </summary>
        public static string MiddleButtonDragger {
            get {
                return ResourceManager.GetString("MiddleButtonDragger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NestedEntity 的本地化字符串。
        /// </summary>
        public static string NestedEntity {
            get {
                return ResourceManager.GetString("NestedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orbit 的本地化字符串。
        /// </summary>
        public static string Orbit {
            get {
                return ResourceManager.GetString("Orbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan 的本地化字符串。
        /// </summary>
        public static string Pan {
            get {
                return ResourceManager.GetString("Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render Mode 的本地化字符串。
        /// </summary>
        public static string RenderMode {
            get {
                return ResourceManager.GetString("RenderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RightButtonDragger 的本地化字符串。
        /// </summary>
        public static string RightButtonDragger {
            get {
                return ResourceManager.GetString("RightButtonDragger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Image As... 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show FPS 的本地化字符串。
        /// </summary>
        public static string ShowFPS {
            get {
                return ResourceManager.GetString("ShowFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Image in New Window 的本地化字符串。
        /// </summary>
        public static string ShowImageInNewWindow {
            get {
                return ResourceManager.GetString("ShowImageInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Properties 的本地化字符串。
        /// </summary>
        public static string ShowProperties {
            get {
                return ResourceManager.GetString("ShowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show ViewCube 的本地化字符串。
        /// </summary>
        public static string ShowViewCube {
            get {
                return ResourceManager.GetString("ShowViewCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show WCS 的本地化字符串。
        /// </summary>
        public static string ShowWCS {
            get {
                return ResourceManager.GetString("ShowWCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple 3D Viewer 的本地化字符串。
        /// </summary>
        public static string Simple3DViewer {
            get {
                return ResourceManager.GetString("Simple3DViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubGeometry 的本地化字符串。
        /// </summary>
        public static string SubGeometry {
            get {
                return ResourceManager.GetString("SubGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unhandled Exception 的本地化字符串。
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception has occurred. The application will now exit. 的本地化字符串。
        /// </summary>
        public static string UnhandledExceptionExit {
            get {
                return ResourceManager.GetString("UnhandledExceptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
